// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui_redo

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_Container1 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Container2 = NULL;lv_obj_t *ui_Chart1 = NULL;lv_obj_t *ui_Container3 = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_Image2 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 1024);
lv_obj_set_height( ui_Panel1, 328);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, 6 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_Panel1);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 944);
lv_obj_set_height( ui_Container1, 50);
lv_obj_set_x( ui_Container1, -288 );
lv_obj_set_y( ui_Container1, -130 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_Label1 = lv_label_create(ui_Container1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"14.1V");
lv_obj_set_style_text_font(ui_Label1, &ui_font_bitcount_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Container1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"12:12");
lv_obj_set_style_text_font(ui_Label2, &ui_font_bitcount_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_Panel1);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 971);
lv_obj_set_height( ui_Container2, 215);
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

ui_Chart1 = lv_chart_create(ui_Container2);
lv_obj_set_width( ui_Chart1, 556);
lv_obj_set_height( ui_Chart1, 193);
lv_obj_set_x( ui_Chart1, -310 );
lv_obj_set_y( ui_Chart1, -126 );
lv_obj_set_align( ui_Chart1, LV_ALIGN_CENTER );
lv_chart_set_type( ui_Chart1, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_Chart1, 20);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 0, 0, false, 25);
lv_chart_series_t* ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x08B2FF), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Chart1_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0,0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
lv_obj_set_style_bg_color(ui_Chart1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Chart1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Chart1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Chart1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Chart1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_line_width(ui_Chart1, 7, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_line_rounded(ui_Chart1, true, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_Container3 = lv_obj_create(ui_Container2);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, 323);
lv_obj_set_height( ui_Container3, 240);
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_OVERFLOW_VISIBLE);
lv_obj_add_flag(ui_Container3, LV_OBJ_FLAG_OVERFLOW_VISIBLE);

ui_Image1 = lv_img_create(ui_Container3);
lv_img_set_src(ui_Image1, &boost_gauge_transparent);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);
lv_obj_set_x( ui_Image1, 0 );
lv_obj_set_y( ui_Image1, 6 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );

ui_Image2 = lv_img_create(ui_Container3);
lv_img_set_src(ui_Image2, &gauge_needle);
lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);
lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);
lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
lv_obj_set_x(ui_Image2, 0);
lv_obj_set_y(ui_Image2, 65);
lv_img_set_pivot(ui_Image2, 160, 180);
lv_img_set_angle(ui_Image2, -600); 

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Panel1= NULL;
ui_Container1= NULL;
ui_Label1= NULL;
ui_Label2= NULL;
ui_Container2= NULL;
ui_Chart1= NULL;
ui_Container3= NULL;
ui_Image1= NULL;
ui_Image2= NULL;

}
