// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ui_redo

#ifndef _UI_REDO_UI_H
#define _UI_REDO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_boost_gauge_transparent_png);   // assets/boost_gauge_transparent.png
LV_IMG_DECLARE( ui_img_gauge_needle_png);   // assets/gauge_needle.png

// FONTS
LV_FONT_DECLARE( ui_font_bitcount_40);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
